### ISSUE TITLE
The kancolle will not start.

### ISSUE THREAD

**Issue by atsu2348** [gre4bee/ElectronicObserver#184]
I am using ver. 5.1.8.0. When I start the software, the image is displayed and the browser does not start. Is there a solution?
<img width="238" alt="image" src="https://user-images.githubusercontent.com/22574545/173233844-83c92dbb-ec16-4cc6-8c3e-78ea8d3c907a.png">

**Comment by myangelkamikaze** [comment]
Which version did you use before?
Is there any info in log view?

**Comment by atsu2348** [comment]
> Which version did you use before?

Before 5.1.7.0

> Is there any info in log view?

Error Report [ver. 5.1.8.0]: 2022/06/12 21:55:35
Error: Exception
Exception of type 'System.Exception' was thrown.
Additional info: ブラウザの終了中にエラーが発生しました。
Stack trace:
   at ElectronicObserver.Window.FormBrowserHost.get_Browser() in F:\ElectronicObserver\ElectronicObserver\Window\FormBrowserHost.cs:line 55
   at ElectronicObserver.Window.FormBrowserHost.CloseBrowser() in F:\ElectronicObserver\ElectronicObserver\Window\FormBrowserHost.cs:line 511

**Comment by myangelkamikaze** [comment]
That error probably isn't the cause.
There weren't any real changes to browser so it's really odd that it wouldn't start anymore...
Can you check your WebView2 version? It's under Apps & features in windows
![image](https://user-images.githubusercontent.com/40002167/173235700-ba5e7dd6-6820-46a0-9c18-aeb25a340151.png)

**Comment by atsu2348** [comment]
> Can you check your WebView2 version?
101.0.1210.53

**Comment by atsu2348** [comment]
Also, I have been running it on drive E, but the logs seem to reference drive F. I have never run it on drive F, so I don't know why.
I have never run it on drive F, so I don't know why.

**Comment by myangelkamikaze** [comment]
Those paths reference the source files on the computer the release was built. They're unrelated to the files on your computer.

I'm guessing you tried to restart, and it didn't get fixed. Can you try running it as admin? There might be a permission problem, but that would be very strange too since nothing really changed from the previous version...

**Comment by myangelkamikaze** [comment]
Try looking in event viewer if there's any error showing there. Source should be .NET Runtime.

![image](https://user-images.githubusercontent.com/40002167/173238313-d6e04ef2-6757-4472-8bed-e9ab4eb9cdab.png)

**Comment by atsu2348** [comment]
> Try looking in event viewer if there's any error showing there.

Application: EOBrowser.exe
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Jot, Version=2.1.11.0, Culture=neutral, PublicKeyToken=6b498f69c5f88322'. 指定されたファイルが見つかりません。
File name: 'Jot, Version=2.1.11.0, Culture=neutral, PublicKeyToken=6b498f69c5f88322'
   at Browser.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Browser.App.Main()

<img width="588" alt="image" src="https://user-images.githubusercontent.com/22574545/173238551-14a869fe-b19e-4645-afd9-c42f5667901a.png">

**Comment by myangelkamikaze** [comment]
Wait what, how's that possible...
It's supposedly missing a dll, but the main app is using the same dll so if that was missing it shouldn't be starting at all...
How exactly did you perform the update?

**Comment by atsu2348** [comment]
It was the software that was restarted, I had not yet tried restarting the OS. I will try it now.

**Comment by myangelkamikaze** [comment]
Oh no, restarting 七四式 should be enough.
Can you check in the 七四式 if there's EOUpdater.exe? If there is, try running that. It will redownload the latest version.
If it's not there, try downloading the latest [zip file](https://github.com/gre4bee/ElectronicObserver/releases/download/5.1.8/ElectronicObserver518EN.zip) again and copying all the files from the zip file in your 七四式 folder.

**Comment by atsu2348** [comment]
> How exactly did you perform the update?
I updated by selecting YES to the update confirmation that pops up as a popup at startup.
When I closed it once and started it up after the update, the version had not changed and I updated again.

I started EOUpdater.exe, and now the 74th formula starts correctly. It appears there was a problem with the update process.
Thank you for your support.

**Comment by myangelkamikaze** [comment]
Ah, good to hear!
