### ISSUE TITLE
Translations not downloaded on first run

### ISSUE THREAD

**Issue by gre4bee** [gre4bee/ElectronicObserver#33]
translations for EO not downloaded on first run.

Error Log:
[2020/08/13 19:14:08][3] : ConfigurationData: Settings\Configuration.xml does not exists.
[2020/08/13 19:14:10][2] : Electronic Observer is starting...
[2020/08/13 19:14:10][2] : Assets/Record/ShipParameterRecord.csv has been copied.
[2020/08/13 19:14:10][3] : Failed to load records.
[2020/08/13 19:14:10][3] : DestinationData: File does not exists.
[2020/08/13 19:14:10][3] : EquipmentTranslationData: File does not exists.
[2020/08/13 19:14:10][3] : MissionTranslationData: File does not exists.
[2020/08/13 19:14:10][3] : OperationData: File does not exists.
[2020/08/13 19:14:10][3] : QuestTranslationData: File does not exists.
[2020/08/13 19:14:10][3] : ShipTranslationData: File does not exists.
[2020/08/13 19:14:10][2] : Assets/Settings/ShipGroups.xml has been copied.
[2020/08/13 19:14:10][3] : QuestProgressManager: Settings\QuestProgress.xml does not exists.
[2020/08/13 19:14:11][3] : No window layout found.
[2020/08/13 19:14:17][3] : Failed to obtain update data. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Terry\AppData\Local\ElectronicObserver\Translations\update.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ElectronicObserver.Utility.SoftwareUpdater.CheckUpdateAsync() in F:\Program Files\Dropbox\EO Sync\ElectronicObserver\Utility\SoftwareUpdater.cs:line 109
[2020/08/13 19:14:17][3] : Startup complete.
[2020/08/13 19:14:17][3] : You are currently using the latest version (2020/07/23 release).
[2020/08/13 19:17:29][3] : Failed to obtain update data. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Terry\AppData\Local\ElectronicObserver\Translations\update.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ElectronicObserver.Utility.SoftwareUpdater.CheckUpdateAsync() in F:\Program Files\Dropbox\EO Sync\ElectronicObserver\Utility\SoftwareUpdater.cs:line 109

version 4.6.1 Preview.

Workaround: Download the translations from the repository and manually place them into directory to work.

**Comment by myangelkamikaze** [comment]
The error happened cause the Translations folder wasn't created before making the update.json file. Fixed now.
