### ISSUE TITLE
レイアウトを固定後、アプリが起動しない

### ISSUE THREAD

**Issue by tyochiai** [gre4bee/ElectronicObserver#516]
5.3.9.0 で追加された「ランキング」タブをメインウィンドウから別ウィンドウに移動し（これは成功）、レイアウトのロック（ファイル -> レイアウト -> 調整 -> レイアウトのロック）をしたところでアプリケーションが終了し、その後起動してもスプラッシュとブラウザウィンドウ？が表示された後にそのまま終了してしまいます。
お手数ですが、確認すべき点や追加で必要な情報、起動させるのに必要な手順等があれば教えてください。
 
Windows のイベントビューアーの「管理イベント」には３つのイベントが記録されており、１つは下記の通り .NET Runtime に関するものでした。残り２つは同じ内容で、Application Error に関するものでした。

ソース: .NET Runtime
```
Application: ElectronicObserver.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at ElectronicObserver.Behaviors.PersistentColumns.PersistentColumnsBehavior.WasGridInitialized() in F:\ElectronicObserver\ElectronicObserver\Behaviors\PersistentColumns\PersistentColumnsBehavior.cs:line 105
   at ElectronicObserver.Behaviors.PersistentColumns.PersistentColumnsBehavior.DataGridLoaded(Object sender, RoutedEventArgs e) in F:\ElectronicObserver\ElectronicObserver\Behaviors\PersistentColumns\PersistentColumnsBehavior.cs:line 110
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

ソース: Application Error
```
障害が発生しているアプリケーション名: ElectronicObserver.exe、バージョン: 5.3.9.0、タイム スタンプ: 0xad570b12
障害が発生しているモジュール名: KERNELBASE.dll、バージョン: 10.0.22621.4541、タイム スタンプ: 0x8ca6fab8
例外コード: 0xe0434352
障害オフセット: 0x000000000005fb4c
障害が発生しているプロセス ID: 0x0x4D7C
障害が発生しているアプリケーションの開始時刻: 0x0x1DB48E891656A56
障害が発生しているアプリケーション パス: D:\kancolle\ElectronicObserverEN\ElectronicObserver.exe
障害が発生しているモジュール パス: C:\WINDOWS\System32\KERNELBASE.dll
レポート ID: 14e6080b-4da3-4e79-bbe1-fdf8c6c54edf
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID: 
```

よろしくお願いします。

**Comment by myangelkamikaze** [comment]
Thanks for the detailed information, I was able to reproduce the error.

repro:
have ranking view in a floating state
lock layout
persistent column behavior will throw an exception because ColumnProperties are null

current fix:
look for your layout file (by default it's `Settings\Layout\Default.xml`)
make a backup of it in case there's any issues during the fix
search for "SenkaLeaderboard"
delete that part
![image](https://github.com/user-attachments/assets/c8c78449-cbae-4a0a-93db-ca49e1f7fc3d)

**Comment by myangelkamikaze** [comment]
Ah, I actually wanted to write that the fix is available in 5.3.10 and close this issue, but forgot about it w
Thanks for confirming the fix works.
